local maindomane = "jizzy.de"
 Domanes["www.Jizzy-Club.de"]=maindomane
 Domanes["Jizzy"]=maindomane
 Domanes["Jizzy.com"]=maindomane
 Domanes["Jizzy-Club"]=maindomane
 Domanes["www.Jizzy.de"]=maindomane
 Domanes["www.Party.de"]=maindomane
 Domanes["Club"]=maindomane
 Domanes["www.Club.de"]=maindomane

function Jizzy_func ()
img = createBasicPage ( "black" )
gImage["Jizzy2"] = guiCreateStaticImage(-1,0,401,5,"images/colors/c_red.jpg",false,img)
gImage["Jizzy3"] = guiCreateStaticImage(393,0,7,299,"images/colors/c_red.jpg",false,img)
gImage["Jizzy4"] = guiCreateStaticImage(-1,293,397,6,"images/colors/c_red.jpg",false,img)
gImage["Jizzy5"] = guiCreateStaticImage(-2,2,8,294,"images/colors/c_red.jpg",false,img)
gLabel["Jizzy1"] = guiCreateLabel(71,10,250,59,"Jizzy's Club",false,img)
guiLabelSetColor(gLabel["Jizzy1"],200,10,0)
guiLabelSetVerticalAlign(gLabel["Jizzy1"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy1"],"left",false)
guiSetFont(gLabel["Jizzy1"],"sa-gothic")
gImage["Jizzy6"] = guiCreateStaticImage(2,68,394,5,"images/colors/c_red.jpg",false,img)
gImage["Jizzy7"] = guiCreateStaticImage(2,85,397,5,"images/colors/c_red.jpg",false,img)
gImage["Jizzy8"] = guiCreateStaticImage(4,72,390,13,"images/colors/c_grey.jpg",false,img)
gLabel["Jizzy2"] = guiCreateLabel(114,72,151,15,"Party bis der Arzt kommt !",false,img)
guiLabelSetColor(gLabel["Jizzy2"],255,0,0)
guiLabelSetVerticalAlign(gLabel["Jizzy2"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy2"],"left",false)
guiSetFont(gLabel["Jizzy2"],"default-bold-small")
gLabel["Jizzy3"] = guiCreateLabel(73,97,241,15,"Sie wollen, dass ihre Party richtig gut wird?",false,img)
guiLabelSetColor(gLabel["Jizzy3"],255,255,255)
guiLabelSetVerticalAlign(gLabel["Jizzy3"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy3"],"left",false)
guiSetFont(gLabel["Jizzy3"],"default-bold-small")
gLabel["Jizzy4"] = guiCreateLabel(87,114,201,17,"Sie haben aber ein zu kleines Haus?",false,img)
guiLabelSetColor(gLabel["Jizzy4"],255,255,255)
guiLabelSetVerticalAlign(gLabel["Jizzy4"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy4"],"left",false)
guiSetFont(gLabel["Jizzy4"],"default-bold-small")
gLabel["Jizzy5"] = guiCreateLabel(35,145,330,47,"Feiern sie im JizzyClub !",false,img)
guiLabelSetColor(gLabel["Jizzy5"],200,200,200)
guiLabelSetVerticalAlign(gLabel["Jizzy5"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy5"],"left",false)
guiSetFont(gLabel["Jizzy5"],"sa-header")
gImage["Jizzy9"] = guiCreateStaticImage(2,140,391,5,"images/colors/c_red.jpg",false,img)
gLabel["Jizzy6"] = guiCreateLabel(98,191,175,15,"Fuer Getraenke wird gesorgt !",false,img)
guiLabelSetColor(gLabel["Jizzy6"],255,255,255)
guiLabelSetVerticalAlign(gLabel["Jizzy6"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy6"],"left",false)
guiSetFont(gLabel["Jizzy6"],"default-bold-small")
gLabel["Jizzy7"] = guiCreateLabel(109,209,144,14,"Fuer Frauen wird gesorgt !",false,img)
guiLabelSetColor(gLabel["Jizzy7"],255,255,255)
guiLabelSetVerticalAlign(gLabel["Jizzy7"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy7"],"left",false)
guiSetFont(gLabel["Jizzy7"],"default-bold-small")
gImage["Jizzy10"] = guiCreateStaticImage(2,229,392,9,"images/colors/c_red.jpg",false,img)
gLabel["Jizzy8"] = guiCreateLabel(58,239,286,47,"Alles zu Top Preisen!",false,img)
guiLabelSetColor(gLabel["Jizzy8"],255,255,255)
guiLabelSetVerticalAlign(gLabel["Jizzy8"],"top")
guiLabelSetHorizontalAlign(gLabel["Jizzy8"],"left",false)
guiSetFont(gLabel["Jizzy8"],"sa-header")
end
addEvent ( "jizzy.de", true )
addEventHandler ( "jizzy.de", getRootElement(), Jizzy_func )