function replaceModels()
	txd16 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd16, 14399)
	col16 = engineLoadCOL('carsys/tuning/neon/objects/Red.col')
	dff16 = engineLoadDFF('carsys/tuning/neon/objects/Red.dff', 0)
	engineReplaceCOL(col16, 14399)
	engineReplaceModel(dff16, 14399)
	engineReplaceCOL(col16, 14399)
	txd17 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd17, 14400)
	col17 = engineLoadCOL('carsys/tuning/neon/objects/Blue.col')
	dff17 = engineLoadDFF('carsys/tuning/neon/objects/Blue.dff', 0)
	engineReplaceCOL(col17, 14400)
	engineReplaceModel(dff17, 14400)
	engineReplaceCOL(col17, 14400)
	txd18 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd18, 14401)
	col18 = engineLoadCOL('carsys/tuning/neon/objects/Green.col')
	dff18 = engineLoadDFF('carsys/tuning/neon/objects/Green.dff', 0)
	engineReplaceCOL(col18, 14401)
	engineReplaceModel(dff18, 14401)
	engineReplaceCOL(col18, 14401)
	txd19 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd19, 14402)
	col19 = engineLoadCOL('carsys/tuning/neon/objects/Yellow.col')
	dff19 = engineLoadDFF('carsys/tuning/neon/objects/Yellow.dff', 0)
	engineReplaceCOL(col19, 14402)
	engineReplaceModel(dff19, 14402)
	engineReplaceCOL(col19, 14402)
	txd20 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd20, 14403)
	col20 = engineLoadCOL('carsys/tuning/neon/objects/Pink.col')
	dff20 = engineLoadDFF('carsys/tuning/neon/objects/Pink.dff', 0)
	engineReplaceCOL(col20, 14403)
	engineReplaceModel(dff20, 14403)
	engineReplaceCOL(col20, 14403)
	txd21 = engineLoadTXD('carsys/tuning/neon/objects/MatTextures.txd')
	engineImportTXD(txd21, 14404)
	col21 = engineLoadCOL('carsys/tuning/neon/objects/White.col')
	dff21 = engineLoadDFF('carsys/tuning/neon/objects/White.dff', 0)
	engineReplaceCOL(col21, 14404)
	engineReplaceModel(dff21, 14404)
	engineReplaceCOL(col21, 14404)
end
addEventHandler("onClientResourceStart", getResourceRootElement(getThisResource()), replaceModels)

local neonColors = {["red"] = 14399, ["blue"] = 14400, ["green"] = 14401, ["yellow"] = 14402, ["pink"] = 14403, ["white"] = 14404}

function createNeon(color, vehicle)
	if not color then return end
	if not vehicle then return end
	if not neonColors[color] then return end
	local zDis = getElementDistanceFromCentreOfMassToBaseOfModel(vehicle)
	triggerServerEvent("createNeon", getLocalPlayer(), color, vehicle, zDis)
end
addEvent("createNeonS", true)
addEventHandler("createNeonS", getRootElement(), createNeon)
	