local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16747)
local dff = engineLoadDFF("pod_suf_biale.dff", 16747)
			engineReplaceModel(dff, 16747)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16747)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16746)
local dff = engineLoadDFF("pod_suf_dyw.dff", 16746)
			engineReplaceModel(dff, 16746)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16746)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16745)
local dff = engineLoadDFF("pod_suf_dyw2.dff", 16745)
			engineReplaceModel(dff, 16745)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16745)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16744)
local dff = engineLoadDFF("pod_suf_pan.dff", 16744)
			engineReplaceModel(dff, 16744)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16744)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16743)
local dff = engineLoadDFF("pod_suf_pan2.dff", 16743)
			engineReplaceModel(dff, 16743)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16743)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16742)
local dff = engineLoadDFF("pod_suf_plytki.dff", 16742)
			engineReplaceModel(dff, 16742)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16742)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16741)
local dff = engineLoadDFF("pod_suf_plytki2.dff", 16741)
			engineReplaceModel(dff, 16741)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16741)
--------------------------------------------------------------
local txd = engineLoadTXD("pod_suf_tex.txd")
			engineImportTXD(txd, 16740)
local dff = engineLoadDFF("pod_suf_plytki3.dff", 16740)
			engineReplaceModel(dff, 16740)
local col = engineLoadCOL ( "pod_suf_col.col" )
			engineReplaceCOL ( col, 16740)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10229)
local dff = engineLoadDFF("sciana_biala.dff", 10229)
			engineReplaceModel(dff, 10229)
local col = engineLoadCOL ( "sciana_col.col" )
			engineReplaceCOL ( col, 10229)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10230)
local dff = engineLoadDFF("sciana_blekitna.dff", 10230)
			engineReplaceModel(dff, 10230)
local col = engineLoadCOL ( "sciana_col.col" )
			engineReplaceCOL ( col, 10230)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10231)
local dff = engineLoadDFF("sciana_zielona.dff", 10231)
			engineReplaceModel(dff, 10231)
local col = engineLoadCOL ( "sciana_col.col" )
			engineReplaceCOL ( col, 10231)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10228)
local dff = engineLoadDFF("sciana_kremowa.dff", 10228)
			engineReplaceModel(dff, 10228)
local col = engineLoadCOL ( "sciana_col.col" )
			engineReplaceCOL ( col, 10228)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10227)
local dff = engineLoadDFF("sciana_drzwi_biala.dff", 10227)
			engineReplaceModel(dff, 10227)
local col = engineLoadCOL ( "sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 10227)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 16739)
local dff = engineLoadDFF("sciana_drzwi_blekitna.dff", 16739)
			engineReplaceModel(dff, 16739)
local col = engineLoadCOL ( "sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 16739)
--------------------------------------------------------------
local txd = engineLoadTXD("sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 16738)
local dff = engineLoadDFF("sciana_drzwi_zielona.dff", 16738)
			engineReplaceModel(dff, 16738)
local col = engineLoadCOL ( "sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 16738)
--------------------------------------------------------------
local txd = engineLoadTXD("devone.txd")
			engineImportTXD(txd, 2028)
local dff = engineLoadDFF("devone.dff", 2028)
			engineReplaceModel(dff, 2028)
local col = engineLoadCOL ( "devone.col" )
			engineReplaceCOL ( col, 2028)
--------------------------------------------------------------
local txd = engineLoadTXD("devps.txd")
			engineImportTXD(txd, 1719)
local dff = engineLoadDFF("devps.dff", 1719)
			engineReplaceModel(dff, 1719)
local col = engineLoadCOL ( "devps.col" )
			engineReplaceCOL ( col, 1719)
--------------------------------------------------------------
local txd = engineLoadTXD("hqtv1.txd")
			engineImportTXD(txd, 1429)
local dff = engineLoadDFF("hqtv1.dff", 1429)
			engineReplaceModel(dff, 1429)
local col = engineLoadCOL ( "hqtv1.col" )
			engineReplaceCOL ( col, 1429)
--------------------------------------------------------------
local txd = engineLoadTXD("lowtv1.txd")
			engineImportTXD(txd, 14772)
local dff = engineLoadDFF("lowtv1.dff", 14772)
			engineReplaceModel(dff, 14772)
local col = engineLoadCOL ( "lowtv1.col" )
			engineReplaceCOL ( col, 14772)
--------------------------------------------------------------
local txd = engineLoadTXD("mhifi1.txd")
			engineImportTXD(txd, 1809)
local dff = engineLoadDFF("mhifi1.dff", 1809)
			engineReplaceModel(dff, 1809)
local col = engineLoadCOL ( "mhifi1.col" )
			engineReplaceCOL ( col, 1809)
--------------------------------------------------------------
local txd = engineLoadTXD("mhifi2.txd")
			engineImportTXD(txd, 2225)
local dff = engineLoadDFF("mhifi2.dff", 2225)
			engineReplaceModel(dff, 2225)
local col = engineLoadCOL ( "mhifi2.col" )
			engineReplaceCOL ( col, 2225)
--------------------------------------------------------------
local txd = engineLoadTXD("mhifi3.txd")
			engineImportTXD(txd, 2227)
local dff = engineLoadDFF("mhifi3.dff", 2227)
			engineReplaceModel(dff, 2227)
local col = engineLoadCOL ( "mhifi3.col" )
			engineReplaceCOL ( col, 2227)
--------------------------------------------------------------
local txd = engineLoadTXD("mtv1.txd")
			engineImportTXD(txd, 1781)
local dff = engineLoadDFF("mtv1.dff", 1781)
			engineReplaceModel(dff, 1781)
local col = engineLoadCOL ( "mtv1.col" )
			engineReplaceCOL ( col, 1781)
--------------------------------------------------------------
local txd = engineLoadTXD("mtv2.txd")
			engineImportTXD(txd, 1750)
local dff = engineLoadDFF("mtv2.dff", 1750)
			engineReplaceModel(dff, 1750)
local col = engineLoadCOL ( "mtv2.col" )
			engineReplaceCOL ( col, 1750)
--------------------------------------------------------------
local txd = engineLoadTXD("mtv3.txd")
			engineImportTXD(txd, 1749)
local dff = engineLoadDFF("mtv3.dff", 1749)
			engineReplaceModel(dff, 1749)
local col = engineLoadCOL ( "mtv3.col" )
			engineReplaceCOL ( col, 1749)
--------------------------------------------------------------
local txd = engineLoadTXD("mtv4.txd")
			engineImportTXD(txd, 1751)
local dff = engineLoadDFF("mtv4.dff", 1751)
			engineReplaceModel(dff, 1751)
local col = engineLoadCOL ( "mtv4.col" )
			engineReplaceCOL ( col, 1751)
--------------------------------------------------------------
local txd = engineLoadTXD("protv1.txd")
			engineImportTXD(txd, 1792)
local dff = engineLoadDFF("protv1.dff", 1792)
			engineReplaceModel(dff, 1792)
local col = engineLoadCOL ( "protv1.col" )
			engineReplaceCOL ( col, 1792)
--------------------------------------------------------------
local txd = engineLoadTXD("protv2.txd")
			engineImportTXD(txd, 1791)
local dff = engineLoadDFF("protv2.dff", 1791)
			engineReplaceModel(dff, 1791)
local col = engineLoadCOL ( "protv2.col" )
			engineReplaceCOL ( col, 1791)
--------------------------------------------------------------
local txd = engineLoadTXD("tvrem.txd")
			engineImportTXD(txd, 2344)
local dff = engineLoadDFF("tvrem.dff", 2344)
			engineReplaceModel(dff, 2344)
--------------------------------------------------------------
local txd = engineLoadTXD("pumpkin.txd")
			engineImportTXD(txd, 8981)
local dff = engineLoadDFF("pumpkin.dff", 8981)
			engineReplaceModel(dff, 8981)
local col = engineLoadCOL ( "pumpkin.col" )
			engineReplaceCOL ( col, 8981)
--------------------------------------------------------------
local txd = engineLoadTXD("kruton9000.txd")
			engineImportTXD(txd, 2014)
local dff = engineLoadDFF("kruton9000.dff", 2014)
			engineReplaceModel(dff, 2014)
local col = engineLoadCOL ( "kruton9000.col" )
			engineReplaceCOL ( col, 2014)
--------------------------------------------------------------
local txd = engineLoadTXD("ramp.txd")
			engineImportTXD(txd, 2015)
local dff = engineLoadDFF("ramp.dff", 2015)
			engineReplaceModel(dff, 2015)
local col = engineLoadCOL ( "ramp.col" )
			engineReplaceCOL ( col, 2015)
--------------------------------------------------------------
local txd = engineLoadTXD("welder.txd")
			engineImportTXD(txd, 2016)
local dff = engineLoadDFF("welder.dff", 2016)
			engineReplaceModel(dff, 2016)
local col = engineLoadCOL ( "welder.col" )
			engineReplaceCOL ( col, 2016)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool.txd")
			engineImportTXD(txd, 2018)
local dff = engineLoadDFF("dev_tool.dff", 2018)
			engineReplaceModel(dff, 2018)
local col = engineLoadCOL ( "dev_tool.col" )
			engineReplaceCOL ( col, 2018)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool2.txd")
			engineImportTXD(txd, 2019)
local dff = engineLoadDFF("dev_tool2.dff", 2019)
			engineReplaceModel(dff, 2019)
local col = engineLoadCOL ( "dev_tool2.col" )
			engineReplaceCOL ( col, 2019)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool3.txd")
			engineImportTXD(txd, 2020)
local dff = engineLoadDFF("dev_tool3.dff", 2020)
			engineReplaceModel(dff, 2020)
local col = engineLoadCOL ( "dev_tool3.col" )
			engineReplaceCOL ( col, 2020)
--------------------------------------------------------------
local txd = engineLoadTXD("tire.txd")
			engineImportTXD(txd, 2021)
local dff = engineLoadDFF("tire.dff", 2021)
			engineReplaceModel(dff, 2021)
local col = engineLoadCOL ( "tire.col" )
			engineReplaceCOL ( col, 2021)
--------------------------------------------------------------
local txd = engineLoadTXD("tire2.txd")
			engineImportTXD(txd, 2022)
local dff = engineLoadDFF("tire2.dff", 2022)
			engineReplaceModel(dff, 2022)
local col = engineLoadCOL ( "tire2.col" )
			engineReplaceCOL ( col, 2022)
--------------------------------------------------------------
local txd = engineLoadTXD("tools.txd")
			engineImportTXD(txd, 1630)
local dff = engineLoadDFF("tools.dff", 1630)
			engineReplaceModel(dff, 1630)
local col = engineLoadCOL ( "tools.col" )
			engineReplaceCOL ( col, 1630)
--------------------------------------------------------------
local txd = engineLoadTXD("choinka.txd")
			engineImportTXD(txd, 18000)
local dff = engineLoadDFF("choinka.dff", 18000)
			engineReplaceModel(dff, 18000)
local col = engineLoadCOL ( "choinka.col" )
			engineReplaceCOL ( col, 18000)
--------------------------------------------------------------
local txd = engineLoadTXD("prezenty.txd")
			engineImportTXD(txd, 1942)
local dff = engineLoadDFF("prezenty.dff", 1942)
			engineReplaceModel(dff, 1942)
local col = engineLoadCOL ( "prezenty.col" )
			engineReplaceCOL ( col, 1942)
--------------------------------------------------------------
local txd = engineLoadTXD("skarpety.txd")
			engineImportTXD(txd, 1943)
local dff = engineLoadDFF("skarpety.dff", 1943)
			engineReplaceModel(dff, 1943)
local col = engineLoadCOL ( "skarpety.col" )
			engineReplaceCOL ( col, 1943)
--------------------------------------------------------------
--W każdej takiej "wydzielonej" sekcji przypisujesz 1 model pod konkretny model z gry.
--Listę obiektów masz podaną,

-- DEVGAMING 2.5
local txd = engineLoadTXD("dev25/int_tex.txd")

--------------------------------------------------------------
engineImportTXD(txd, 8594)
local dff = engineLoadDFF("dev25/floor_1.dff", 8594)
engineReplaceModel(dff, 8594)
local col = engineLoadCOL ( "dev25/floor_1.col")
engineReplaceCOL(col, 8594)
--------------------------------------------------------------
engineImportTXD(txd, 8593)
local dff = engineLoadDFF("dev25/floor_2.dff", 8593)
engineReplaceModel(dff, 8593)
local col = engineLoadCOL ( "dev25/floor_2.col")
engineReplaceCOL(col, 8593)
--------------------------------------------------------------
engineImportTXD(txd, 8087)
local dff = engineLoadDFF("dev25/floor_3.dff", 8087)
engineReplaceModel(dff, 8087)
local col = engineLoadCOL ( "dev25/floor_3.col")
engineReplaceCOL(col, 8087)
--------------------------------------------------------------
engineImportTXD(txd, 8086)
local dff = engineLoadDFF("dev25/wall_1.dff", 8086)
engineReplaceModel(dff, 8086)
local col = engineLoadCOL ( "dev25/wall_1.col")
engineReplaceCOL(col, 8086)
--------------------------------------------------------------
engineImportTXD(txd, 8085)
local dff = engineLoadDFF("dev25/wall_2.dff", 8085)
engineReplaceModel(dff, 8085)
local col = engineLoadCOL ( "dev25/wall_2.col")
engineReplaceCOL(col, 8085)
--------------------------------------------------------------
engineImportTXD(txd, 8084)
local dff = engineLoadDFF("dev25/wall_3.dff", 8084)
engineReplaceModel(dff, 8084)
local col = engineLoadCOL ( "dev25/wall_3.col")
engineReplaceCOL(col, 8084)
--------------------------------------------------------------
engineImportTXD(txd, 8083)
local dff = engineLoadDFF("dev25/wall_4.dff", 8083)
engineReplaceModel(dff, 8083)
local col = engineLoadCOL ( "dev25/wall_4.col")
engineReplaceCOL(col, 8083)
--------------------------------------------------------------
engineImportTXD(txd, 8082)
local dff = engineLoadDFF("dev25/wall_5.dff", 8082)
engineReplaceModel(dff, 8082)
local col = engineLoadCOL ( "dev25/wall_5.col")
engineReplaceCOL(col, 8082)
--------------------------------------------------------------
engineImportTXD(txd, 8081)
local dff = engineLoadDFF("dev25/wall_6.dff", 8081)
engineReplaceModel(dff, 8081)
local col = engineLoadCOL ( "dev25/wall_6.col")
engineReplaceCOL(col, 8081)
--------------------------------------------------------------
engineImportTXD(txd, 8595)
local dff = engineLoadDFF("dev25/wall_7.dff", 8595)
engineReplaceModel(dff, 8595)
local col = engineLoadCOL ( "dev25/wall_7.col")
engineReplaceCOL(col, 8595)
--------------------------------------------------------------